# Generated by Django 3.2.7 on 2022-07-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='se1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='se2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='se3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='se4',
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_num', models.IntegerField(verbose_name='回答番号')),
                ('name', models.CharField(max_length=10, verbose_name='回答')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_q', to='survey.questions', verbose_name='問題番号')),
            ],
            options={
                'verbose_name_plural': '学年',
            },
        ),
    ]
