# Generated by Django 3.2.7 on 2022-07-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20220724_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.CharField(max_length=20, verbose_name='問題'),
        ),
    ]
